apiVersion: v1
kind: ConfigMap
metadata:
  name: blockchain-config
  namespace: blockchain
data:
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  RABBIT_HOST: rabbitmq
  RABBIT_PORT: "5672"
  RABBIT_USER: user
  RABBIT_PASS: pass
  RABBIT_QUEUE_NAME: pending_transactions
