version: '3.8'
services:
  nodo_c:
    image: hit6_nodo_c
    build: ./C/
    networks:
      - red_d

  registro_d:
    image: hit6_registro_d
    build: ./D/
    networks:
      - red_d

networks:
  red_d:
    driver: bridge