# Usa la imagen base de Python
FROM python:3.9

# Establece el directorio de trabajo
WORKDIR /app

# Copia el script al contenedor
COPY programa.py .

# Define la entrada del contenedor para aceptar argumentos
#ENTRYPOINT ["python", "programa.py"]