{
 "title": "Dashboard Ejemplo 3",
 "time": { "from": "2026-02-26T23:12:05.448Z", "to": "2026-02-26T23:22:05.448Z" },
 "panels": [
  {
   "title": "Memoria usada por el coordinador",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{\n  namespace=\"blockchain\",\n  pod=~\"coordinador-.*\",\n  container=\"coordinador\",\n  image!=\"\"\n} / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Salud del scrape del coordinador",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"coordinador\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU del coordinador en milicores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "1000 * sum by (pod) (\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"blockchain\",\n    pod=~\"coordinador-.*\",\n    container=\"coordinador\",\n    image!=\"\"\n  }[5m])\n)\n\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duración estimada de ciclo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(1 / clamp_min(sum(rate(coordinador_cycles_total{job=\"coordinador\",event=\"completed\"}[30m])), 1e-9)) / 60\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workers deseados por dificultad",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "mining_workers_desired{job=\"coordinador\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tendencia de crecimiento de pending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "deriv(coordinador_pending_queue_size{job=\"coordinador\"}[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ciclos completados por hora",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(coordinador_cycles_total{job=\"coordinador\",event=\"completed\"}[15m])) * 3600\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mensajes enviados de mineros al endpoint de resultados",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "coordinador_received_chains_size{job=\"coordinador\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total, pendientes + activas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "coordinador_pending_queue_size{job=\"coordinador\"}\n+\ncoordinador_active_queue_size{job=\"coordinador\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cola pendiente actual",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "coordinador_pending_queue_size{job=\"coordinador\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cola activa actual",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "coordinador_active_queue_size{job=\"coordinador\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ganador promedio por tarea",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le) (\n    rate(coordinador_mining_duration_seconds_bucket{job=\"coordinador\"}[$__rate_interval])\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Promedio minado por prefijo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum by (prefix) (\n  rate(coordinador_mining_duration_seconds_sum{job=\"coordinador\"}[$__rate_interval])\n)\n/\nclamp_min(\n  sum by (prefix) (\n    rate(coordinador_mining_duration_seconds_count{job=\"coordinador\"}[$__rate_interval])\n  ),\n  1e-9\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latencia de validacion de bloques aceptados",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le) (\n    rate(coordinador_block_validation_duration_seconds_bucket{job=\"coordinador\",status=\"accepted\"}[$__rate_interval])\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latencia promedio de validación por status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by (status) (\n  rate(coordinador_block_validation_duration_seconds_sum{job=\"coordinador\"}[$__rate_interval])\n)\n/\nclamp_min(\n  sum by (status) (\n    rate(coordinador_block_validation_duration_seconds_count{job=\"coordinador\"}[$__rate_interval])\n  ),\n  1e-9\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasa de aceptacion de resultados de minado",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "100 *\nsum(rate(coordinador_results_total{job=\"coordinador\",status=\"accepted\"}[$__rate_interval]))\n/\nclamp_min(sum(rate(coordinador_results_total{job=\"coordinador\"}[$__rate_interval])), 1e-9)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rechazos de resultados por stacked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum by (status) (\n  rate(coordinador_results_total{job=\"coordinador\",status!=\"accepted\"}[$__rate_interval])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cantidad de rechazos por stacked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "sum by (status) (\n  rate(coordinador_tx_submitted_total{job=\"coordinador\",status!=\"accepted\"}[$__rate_interval])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ingreso total de resultados de minado",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "sum(rate(coordinador_results_total{job=\"coordinador\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transacciones recibidas por el coordinador",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "sum(rate(coordinador_tx_submitted_total{job=\"coordinador\"}[$__rate_interval]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasa de aceptación de transacciones",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "100 *\nsum(rate(coordinador_tx_submitted_total{job=\"coordinador\",status=\"accepted\"}[$__rate_interval]))\n/\nclamp_min(sum(rate(coordinador_tx_submitted_total{job=\"coordinador\"}[$__rate_interval])), 1e-9)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duración en segundos de tiempo de validacion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "sum (rate(coordinador_block_validation_duration_seconds_sum{status=\"accepted\"}[5m]))\n/\nsum (rate(coordinador_block_validation_duration_seconds_count{status=\"accepted\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tiempo de minado por transaccion calculado por coordinador",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "sum by (prefix) (rate(coordinador_mining_duration_seconds_sum[5m]))\n/\nsum by (prefix) (rate(coordinador_mining_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Porcentaje de transacciones minadas por ciclo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "expr": "100 * avg_over_time(\n  {namespace=\"blockchain\", pod=~\"coordinador.*\"}\n  |= \"Porcentaje de transacciones minadas este ciclo\"\n  | regexp \"Porcentaje de transacciones minadas este ciclo: (?P<pct>[0-9]+(?:\\\\.[0-9]+)?)\"\n  | unwrap pct\n  [2m]\n)\n"
    }
   ]
  },
  {
   "title": "New Panel",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "{job=\"blockchain/coordinador\"} |= ``"
    }
   ]
  }
 ]
}