{
 "title": "Dashboard Final",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Cola activa actual",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "coordinador_active_queue_size{job=\"coordinador\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU del coordinador en milicores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "1000 * sum by (pod) (\n  rate(container_cpu_usage_seconds_total{\n    namespace=\"blockchain\",\n    pod=~\"coordinador-.*\",\n    container=\"coordinador\",\n    image!=\"\"\n  }[5m])\n)\n\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tiempo de minado por transaccion calculado por coordinador",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (prefix) (rate(coordinador_mining_duration_seconds_sum[5m]))\n/\nsum by (prefix) (rate(coordinador_mining_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duración en segundos de tiempo de validacion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum (rate(coordinador_block_validation_duration_seconds_sum{status=\"accepted\"}[5m]))\n/\nsum (rate(coordinador_block_validation_duration_seconds_count{status=\"accepted\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memoria usada por el coordinador",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{\n  namespace=\"blockchain\",\n  pod=~\"coordinador-.*\",\n  container=\"coordinador\",\n  image!=\"\"\n} / 1024 / 1024\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Porcentaje de transacciones minadas por ciclo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "100 * avg_over_time(\n  {namespace=\"blockchain\", pod=~\"coordinador.*\"}\n  |= \"Porcentaje de transacciones minadas este ciclo\"\n  | regexp \"Porcentaje de transacciones minadas este ciclo: (?P<pct>[0-9]+(?:\\\\.[0-9]+)?)\"\n  | unwrap pct\n  [2m]\n)\n"
    }
   ]
  },
  {
   "title": "Cantidad de workers deseados",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "mining_workers_desired{job=\"coordinador\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cola pendiente actual",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "coordinador_pending_queue_size{job=\"coordinador\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transacciones pendientes + activas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "coordinador_pending_queue_size{job=\"coordinador\"}\n+\ncoordinador_active_queue_size{job=\"coordinador\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duración del ciclo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "(1 / clamp_min(sum(rate(coordinador_cycles_total{job=\"coordinador\",event=\"completed\"}[30m])), 1e-9)) / 60\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Coordinador",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "{job=\"blockchain/coordinador\"} |= ``"
    }
   ]
  },
  {
   "title": "Cantidad de mineros que enviaron resultados en el ciclo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "coordinador_received_chains_size{job=\"coordinador\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Minero",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "{job=\"blockchain/minero\"} |= ``"
    }
   ]
  },
  {
   "title": "Pool",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "{job=\"pool/pool\"} |= ``"
    }
   ]
  }
 ]
}