version: '3.8'
services:
  nodo_c:
    image: hit7_nodo_c
    build: ./C/
    networks:
      - red_e

  registro_d:
    image: hit7_registro_d
    build: ./D/
    networks:
      - red_e

networks:
  red_e:
    driver: bridge