services:
  servidor:
    image: servidor
    build: ./servidor/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NGROK_AUTHTOKEN=2vZDU3BXpjAHwSTQMUJ41ws1Wlh_DHoJDuVv1mSSYiTyfipo
    networks:
      - tarea-net
  cliente:
    build:
      context: ./cliente
    depends_on:
      - servidor
    networks:
      - tarea-net

networks:
  tarea-net:
    driver: bridge
    external: true