apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-creator
  namespace: grupo4
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-creator-binding
  namespace: grupo4
subjects:
  - kind: ServiceAccount
    name: grupo4
    namespace: grupo4
roleRef:
  kind: Role
  name: job-creator
  apiGroup: rbac.authorization.k8s.io