import os

INTERVAL_DURATION = 0
AWAIT_RESPONSE_DURATION = 0
MAX_MINING_ATTEMPTS = 0
ACCEPTED_ALGORITHM = ""


URI = os.getenv("HOST_URI", "http://35.244.137.250")
POOL_ID = os.getenv("POOL_ID", "9002")
PROCESSING_TIER = os.getenv("PROCESSING_TIER", 1)

RABBIT_HOST = os.getenv("RABBIT_HOST", "http://35.185.40.225")
RABBIT_USER = os.getenv("RABBIT_USER", "blockchain")
RABBIT_PASS = os.getenv("RABBIT_PASS", "blockchain123")