import os

INTERVAL_DURATION = 0
AWAIT_RESPONSE_DURATION = 0
MAX_MINING_ATTEMPTS = 0
ACCEPTED_ALGORITHM = ""


URI = os.getenv("COORDINATOR_URI", "http://35.244.137.250")
MINER_ID = os.getenv("MINER_ID", "9001")
PROCESSING_TIER = os.getenv("PROCESSING_TIER", 1)