apiVersion: apps/v1
kind: Deployment
metadata:
  name: joiner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joiner
  template:
    metadata:
      labels:
        app: joiner
    spec:
      serviceAccountName: bucket-reader  # Usa el KSA aquí
      nodeSelector:
        role: general
      containers:
      - name: joiner
        image: docker.io/thiagopuyelli/joiner:latest
        ports:
        - containerPort: 8002

---
apiVersion: v1
kind: Service
metadata:
  name: joiner
spec:
  selector:
    app: joiner
  ports:
  - port: 8002
    targetPort: 8002
  type: ClusterIP
