# Imagen base de Python
FROM python:3.9-slim

# Directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el código del programa al contenedor
COPY programa.py /app/

# Comando para ejecutar el programa
CMD ["python", "programa.py"]
